// <auto-generated />
using System;
using ESocial.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESocial.Infrastructure.Migrations
{
    [DbContext(typeof(ESocialDbContext))]
    partial class ESocialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ESocial.Domain.Entities.Empregador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome_razao_social");

                    b.HasKey("Id");

                    b.ToTable("empregadores", (string)null);
                });

            modelBuilder.Entity("ESocial.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("XmlContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("xml_content");

                    b.Property<Guid?>("lote_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("lote_id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("ESocial.Domain.Entities.LoteEventos", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Ambiente")
                        .HasColumnType("int")
                        .HasColumnName("ambiente");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpregadorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("empregador_id");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enviado_em");

                    b.Property<int>("Grupo")
                        .HasColumnType("int")
                        .HasColumnName("grupo_evento");

                    b.Property<int>("NumeroLote")
                        .HasColumnType("int")
                        .HasColumnName("numero_lote");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processado_em");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmpregadorId");

                    b.ToTable("lotes_eventos", (string)null);
                });

            modelBuilder.Entity("ESocial.Domain.Entities.Empregador", b =>
                {
                    b.OwnsOne("ESocial.Domain.ValueObjects.Inscricao", "Inscricao", b1 =>
                        {
                            b1.Property<Guid>("EmpregadorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("nr_inscricao");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("tipo_inscricao");

                            b1.HasKey("EmpregadorId");

                            b1.HasIndex("Numero")
                                .IsUnique();

                            b1.ToTable("empregadores");

                            b1.WithOwner()
                                .HasForeignKey("EmpregadorId");
                        });

                    b.Navigation("Inscricao")
                        .IsRequired();
                });

            modelBuilder.Entity("ESocial.Domain.Entities.Evento", b =>
                {
                    b.HasOne("ESocial.Domain.Entities.LoteEventos", null)
                        .WithMany("Eventos")
                        .HasForeignKey("lote_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("ESocial.Domain.ValueObjects.StatusProcessamento", "Retorno", b1 =>
                        {
                            b1.Property<Guid>("EventoId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CdResposta")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("cd_resposta");

                            b1.Property<string>("DescResposta")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("desc_resposta");

                            b1.HasKey("EventoId");

                            b1.ToTable("eventos");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Retorno");
                });

            modelBuilder.Entity("ESocial.Domain.Entities.LoteEventos", b =>
                {
                    b.HasOne("ESocial.Domain.Entities.Empregador", null)
                        .WithMany("Lotes")
                        .HasForeignKey("EmpregadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ESocial.Domain.ValueObjects.StatusProcessamento", "StatusProcessamento", b1 =>
                        {
                            b1.Property<Guid>("LoteEventosId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CdResposta")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)")
                                .HasColumnName("cd_resposta");

                            b1.Property<string>("DescResposta")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("desc_resposta");

                            b1.HasKey("LoteEventosId");

                            b1.ToTable("lotes_eventos");

                            b1.WithOwner()
                                .HasForeignKey("LoteEventosId");
                        });

                    b.OwnsOne("ESocial.Domain.ValueObjects.ProtocoloEnvio", "Protocolo", b1 =>
                        {
                            b1.Property<Guid>("LoteEventosId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("protocolo");

                            b1.HasKey("LoteEventosId");

                            b1.HasIndex("Valor");

                            b1.ToTable("lotes_eventos");

                            b1.WithOwner()
                                .HasForeignKey("LoteEventosId");
                        });

                    b.Navigation("Protocolo");

                    b.Navigation("StatusProcessamento");
                });

            modelBuilder.Entity("ESocial.Domain.Entities.Empregador", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("ESocial.Domain.Entities.LoteEventos", b =>
                {
                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
